name: Deploy Trackers.txt to GitHub Pages

on:
  push:
    branches:
      - main   # ak máš master, zmeň na master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy Trackers.txt
        run: |
          mkdir -p public/Torrent_Trackers
          cp -v Torrent_Trackers/Trackers.txt public/Torrent_Trackers/Trackers.txt

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
